# Generated by Django 3.0.1 on 2020-01-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Pizza shop title'),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pizza name')),
                ('short_description', models.CharField(max_length=500, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('pizza_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.PizzaShop')),
            ],
        ),
    ]
