# Generated by Django 3.0.1 on 2020-01-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_pizza_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Customer name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.Pizza', verbose_name='Pizza')),
            ],
        ),
    ]
